### ISSUE TITLE
[FEATURE]: Ignored patterns

### ISSUE THREAD

**Issue by aserebryakov** [aserebryakov/filestyle#22]
Allow to configure ignored patterns, that will not be highlighted.

**Comment by aserebryakov** [comment]
GUI part of the feature is implemented.

**Comment by aserebryakov** [comment]
Implemented and merged to `1.0.0-dev`.

**Comment by Markus00000** [comment]
If you leave this issue open, people can keep track of the non-GUI implementation and maybe come up with an idea how to do it.
