### ISSUE TITLE
[BUG]: Switching colorscheme breaks highlighting

### ISSUE THREAD

**Issue by Markus00000** [aserebryakov/filestyle#25]
After switching the colorscheme, highlighting no longer works. Disabling/enabling, deactivating/activating and checking manually do not restore highlighting.

**Comment by aserebryakov** [comment]
Confirmed on 0.7.0

**Comment by aserebryakov** [comment]
Autocommand restoring highlight groups should be added for `ColorScheme` event.

**Comment by aserebryakov** [comment]
Fix pushed to branch `0.7.1-dev`.
