### ISSUE TITLE
Update highlights after textwidth has been changed 

### ISSUE THREAD

**Issue by Markus00000** [aserebryakov/filestyle#27]
If highlights are not updated after changing textwidth, filestyle will incorrectly highlight long lines.

**Comment by aserebryakov** [comment]
This action requires to recreate highlight groups. Unfortunately there is no autocommand that can be used. As a workaround at the moment `call FileStyleCreateHighlightGroups()` can be used.

Anyway it requires an explicit call of  some funciton that will recreate highight groups and will call `FileStyleCheck`.

**Comment by aserebryakov** [comment]
There is no autocommand that can handle a case of changed `textwidth`, so this case can not be handled and user have to execute a command `:FileStyleCheck`.

Issue will not be fixed, the only thing that can be done is mention it in a plug-in documentation.
