### ISSUE TITLE
[BUG:] E803 error when opening a go file using Unite

### ISSUE THREAD

**Issue by sybrandy** [aserebryakov/filestyle#38]
Should be able to duplicate this by opening the tcp_socket.go file in github.com/docker/docker/

Here is the full error message:

[unite.vim] function FileStyleActivate..FileStyleCheck..FileStyleClearBufferMatches, line 3
[unite.vim] Vim(call):E803: ID not found: 10
[unite.vim] Error occurred while executing "open" action!

**Comment by aserebryakov** [comment]
@sybrandy, please provide the full Vim environment including `.vimrc` and `/.vim` in order to reproduce the issue.

**Comment by sybrandy** [comment]
Here you go: https://github.com/sybrandy/local_config

**Comment by aserebryakov** [comment]
@sybrandy Thanks, I will try it.

**Comment by aserebryakov** [comment]
@sybrandy, unfortunaltely I am receiving multiple errors trying to run your environment.
>
Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command: RainbowParenthesesToggle
Press ENTER or type command to continue
Not installed bundles:  ['vim-markdown', 'vim-scala', 'vim-gnupg', 'unite-git-co
nflict.vim', 'vimproc.vim', 'tComment', 'neosnippet-snippets', 'unite.vim', 'vim
-gitgutter', 'numbers.vim', 'rainbow_parentheses.vim', 'taskpaper.vim', 'vim-mul
tiple-cursors', 'vim-unite-history', 'syntastic', 'vim-go', 'vimfiler.vim', 'tab
ular', 'vim-fugitive', 'gundo.vim', 'vim-endwise', 'vim-paren-crosshairs', 'neat
.vim', 'neosnippet', 'gitv', 'redstring.vim', 'unite-outline', 'vimux', 'TaskLis
t.vim', 'neocomplcache', 'L9', 'filestyle', 'lightline.vim', 'QQ.vim', 'vim-eunu
ch', 'indentLine', 'vim-log-syntax']
Press ENTER or type command to continue
Install bundles now?

>Press ENTER or type command to continue

I created a new user to test your case, after cloning NeoBundle I have these messages.

**Comment by sybrandy** [comment]
Did you restart vim after installing the bundles?  That should clear up the errors.  If not, let me know and I can try to come up with a better test case when I have time.

**Comment by aserebryakov** [comment]
@sybrandy Yes, I tried to restart Vim after that, but I had the same errors. Probably, I am missing something.

**Comment by aserebryakov** [comment]
@sybrandy The problem with environment was solved by running `:NeoBundleUpdate`.

**Comment by aserebryakov** [comment]
@sybrandy, I didn't reproduce the issue in your environment. Probably, missing file in `ftplugin`

**Comment by sybrandy** [comment]
I just reproduced it this morning after running `:NeoBundleUpdate`.  I even clean everything out and updated from scratch to no effect.  I'm running this on CentOS 6.7 if that helps.  If I get a chance, I'll try to do some additional debugging.

**Comment by aserebryakov** [comment]
@sybrandy I am running Ubuntu 15.10, the only thing that I can propose is to check if on your OS a new user with your environment still has an issue. But anyway, can you please provide the `vim --version`?

**Comment by sybrandy** [comment]
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 24 2015 02:23:23)
Included patches: 1-207, 209-629
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             -clientserver    +cscope          +emacs_tags      +folding         +keymap          +menu            +mouse_netterm   +netbeans_intg   -python3         -sniff           -tcl             +virtualedit     +writebackup
+arabic          -clipboard       +cursorbind      +eval            -footer          +langmap         +mksession       +mouse_sgr       +path_extra      +quickfix        +startuptime     +terminfo        +visual          -X11
+autocmd         +cmdline_compl   +cursorshape     +ex_extra        +fork()          +libcall         +modify_fname    -mouse_sysmouse  +perl            +reltime         +statusline      +termresponse    +visualextra     -xfontset
-balloon_eval    +cmdline_hist    +dialog_con      +extra_search    +gettext         +linebreak       +mouse           +mouse_urxvt     +persistent_undo +rightleft       -sun_workshop    +textobjects     +viminfo         -xim
-browse          +cmdline_info    +diff            +farsi           -hangul_input    +lispindent      -mouseshape      +mouse_xterm     +postscript      -ruby            +syntax          +title           +vreplace        -xsmp
++builtin_terms  +comments        +digraphs        +file_in_path    +iconv           +listcmds        +mouse_dec       +multi_byte      +printer         +scrollbind      +tag_binary      -toolbar         +wildignore      -xterm_clipboard
+byte_offset     +conceal         -dnd             +find_in_path    +insert_expand   +localmap        +mouse_gpm       +multi_lang      +profile         +signs           +tag_old_static  +user_commands   +wildmenu        -xterm_save
+cindent         +cryptv          -ebcdic          +float           +jumplist        -lua             -mouse_jsbterm   -mzscheme        +python/dyn      +smartindent     -tag_any_white   +vertsplit       +windows         -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux  -ltinfo -lacl -lattr -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/COR
E -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
```

**Comment by aserebryakov** [comment]
@sybrandy It looks like something is missing. I installed CentOS 6.7 on virtual machine and used your environment. The `vimproc.vim` wasn't installed with error `build error`, but I suppose it doesn't matter. Still no error messaged.

**Comment by sybrandy** [comment]
I just reproduced it this morning after running `:NeoBundleUpdate`.  I even clean everything out and updated from scratch to no effect.  I'm running this on CentOS 6.7 if that helps.  If I get a chance, I'll try to do some additional debugging.

**Comment by aserebryakov** [comment]
Issue can't be reproduced.
